kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guardian-admin
subjects:
  - kind: ServiceAccount
    name: guardian
    namespace: knative-guard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardian-cluster-role
