package v1

import (
	"bytes"
	"fmt"
	"time"
)

type SessionProfile struct {
	Alert   bool
	ReqTime time.Time
	Req     ReqProfile
	Resp    RespProfile
	Process ProcessProfile
}

type Pile struct {
	Req     ReqPile
	Resp    RespPile
	Process ProcessPile
}

func (p *Pile) Clear() {
	p.Req.Clear()
	p.Resp.Clear()
	p.Process.Clear()
}

func (p *Pile) Append(a *Pile) {
	p.Req.Append(&a.Req)
	p.Resp.Append(&a.Resp)
	p.Process.Append(&a.Process)
}

func (p *Pile) Marshal() string {
	var description bytes.Buffer
	description.WriteString("{\n")
	description.WriteString(fmt.Sprintf("  Req: %s", p.Req.Marshal(1)))
	description.WriteString(fmt.Sprintf("  Resp: %s", p.Resp.Marshal(1)))
	description.WriteString(fmt.Sprintf("  Process: %s", p.Process.Marshal(1)))
	description.WriteString("}\n")
	return description.String()
}

func (p *Pile) Pile(sp *SessionProfile) {
	p.Req.Add(&sp.Req)
	p.Resp.Add(&sp.Resp)
	p.Process.Add(&sp.Process)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionProfile) DeepCopyInto(out *SessionProfile) {
	*out = *in
	out.ReqTime = in.ReqTime
	in.Req.DeepCopyInto(&out.Req)
	in.Resp.DeepCopyInto(&out.Resp)
	in.Process.DeepCopyInto(&out.Process)
}
