kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: gates.ibmresearch.com
spec:
  group: ibmresearch.com
  scope: Namespaced
  names:
    plural: gates
    singular: gate
    kind: Gates
    listKind: GateList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                    collectorId:
                      type: string
                    minimumLearning:
                      type: integer
                    AllowLimit:
                      type: integer
                    LearnLimit:
                      type: integer
                    roundedMarkers:
                      type: array
                      items:
                        type: string
                    fingerprints:
                      type: array
                      items:
                        type: string
                    histograms:
                      type: array
                      items:
                        type: string
                    integers:
                      type: array
                      items:
                        type: string
                    markers:
                      type: array
                      items:
                        type: string