kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guardian-cluster-role
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - wsecurity.ibmresearch.com
    resources:
      - guardians
