kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: guardians.ibmresearch.com
spec:
  group: ibmresearch.com
  names:
    plural: guardians
    singular: guardian
    kind: Guardians
    listKind: GuardianList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                gateId:
                  type: string
                serviceId:
                  type: string

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
