name: Publish Guard Proxy

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      
      - shell: bash
        run: |
          set -ex
          # Install ko:
          tag=$(curl -s -u "username:${{ github.token }}" https://api.github.com/repos/google/ko/releases/latest | jq -r '.tag_name')
          os=${{ runner.os }}
          if [[ ! -z ${tag} ]]; then
            echo "Installing ko @ ${tag} for ${os}"
            curl -fsL https://github.com/google/ko/releases/download/${tag}/ko_${tag:1}_${os}_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin ko
          fi
          echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin
          # Set KO_DOCKER_REPO for future steps.
          repo=${{ github.repository }} 
          repo=`echo "$repo" | tr '[:upper:]' '[:lower:]'`
          echo "KO_DOCKER_REPO=ghcr.io/${repo}"
          echo "KO_DOCKER_REPO=ghcr.io/${repo}" >> $GITHUB_ENV      
      
      - run: ko build ./cmd/guard-rproxy
    
      
      
    
